FROM node:20.4.0-bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y git openssh-client

RUN npm install -g http-server@14.0.0

RUN mkdir -p -m 0700 ~/.ssh && \
  ssh-keyscan github.com >> ~/.ssh/known_hosts && \
  git config --global url.git@github.com:.insteadOf https://github.com/

RUN --mount=type=ssh,uid=1000 \
  git clone git@github.com:ittokunvim/music.git
